import { redirect } from "next/navigation";
import Link from "next/link";
import { createClient, isSupabaseConfigured } from "@/lib/supabase/server";
import { deleteProject, saveProject, signOut } from "./actions";
import type { Project } from "@/lib/types";

function Field({ name, label, required = false, value = "", type = "text" }: { name: string; label: string; required?: boolean; value?: string; type?: string }) { return <label className="admin-field">{label}<input name={name} type={type} required={required} defaultValue={value} /></label>; }
function ProjectForm({ project }: { project?: Project }) { return <form action={saveProject} className="admin-form"><input type="hidden" name="id" value={project?.id || ""} /><div className="form-grid"><Field name="title" label="Project title" required value={project?.title} /><Field name="slug" label="Slug (created from title if blank)" value={project?.slug} /><label className="admin-field">Type<select name="kind" defaultValue={project?.kind || "UGC Video"}><option>UGC Video</option><option>Technical</option><option>Creative</option></select></label><Field name="year" label="Year" required value={project?.year} /><Field name="client" label="Client" value={project?.client || ""} /><Field name="role" label="Your role" required value={project?.role} /></div><Field name="excerpt" label="Short description" required value={project?.excerpt} /><label className="admin-field">Full description<textarea name="description" required defaultValue={project?.description} rows={4} /></label><div className="form-grid"><Field name="deliverables" label="Deliverables (comma separated)" value={project?.deliverables.join(", ")} /><Field name="tools" label="Tools (comma separated)" value={project?.tools.join(", ")} /><Field name="video_embed_url" label="Public video embed URL" value={project?.video_embed_url || ""} /><Field name="thumbnail_url" label="Thumbnail image URL" value={project?.thumbnail_url || ""} /></div><div className="check-row"><label><input name="featured" type="checkbox" defaultChecked={project?.featured} /> Feature on home</label><label><input name="published" type="checkbox" defaultChecked={project?.published} /> Publish publicly</label></div><button className="button">{project ? "Save changes" : "Add project"}</button></form>; }

export default async function AdminPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) { if (!isSupabaseConfigured()) return <main className="admin-page setup-note"><p className="eyebrow">CMS setup required</p><h1>Connect Supabase<br />to unlock your studio.</h1><p>Add the two public environment variables from <code>.env.example</code>, run <code>supabase/schema.sql</code> in your Supabase SQL editor, then create your administrator account and grant it the <code>admin</code> role as noted in the setup guide.</p><Link href="/">Back to portfolio</Link></main>; const supabase = await createClient(); const { data: { user } } = await supabase.auth.getUser(); if (!user) redirect("/login"); const { data: profile } = await supabase.from("profiles").select("role").eq("id", user.id).maybeSingle(); if (profile?.role !== "admin") redirect("/"); const { data: projects } = await supabase.from("projects").select("*").order("created_at", { ascending: false }); const error = (await searchParams).error; return <main className="admin-page"><header className="admin-header"><div><p className="eyebrow">RJC / studio CMS</p><h1>Projects</h1></div><div><Link href="/" target="_blank">View site ↗</Link><form action={signOut}><button>Sign out</button></form></div></header>{error && <p className="form-error">{error}</p>}<section className="admin-card"><h2>Add new project</h2><ProjectForm /></section><section className="admin-projects"><h2>Current work <span>{projects?.length || 0}</span></h2>{projects?.map((project) => <details key={project.id} className="admin-card"><summary><span>{project.published ? "Live" : "Draft"}</span><strong>{project.title}</strong><small>{project.kind} · {project.year}</small></summary><ProjectForm project={project as Project} /><form action={deleteProject}><input type="hidden" name="id" value={project.id} /><button className="delete-button">Delete project</button></form></details>)}</section></main>; }
